import { InvestmentPlanData, FarmProject } from "./firebaseServices";

export const DEFAULT_INVESTMENT_PLANS: Omit<InvestmentPlanData, "id" | "createdAt">[] = [
  {
    name: "Starter Plan",
    description: "Perfect for new investors",
    minInvestment: 20000,
    maxInvestment: 49999,
    roiPercentage: 18,
    durationDays: 90,
    biWeeklyPayout: 1500,
    popular: false,
    featured: false,
    features: ["18% ROI", "3 Months Duration", "Bi-weekly Payouts", "24/7 Support"],
    active: true,
  },
  {
    name: "Bronze Plan",
    description: "Grow your investment steadily",
    minInvestment: 50000,
    maxInvestment: 99999,
    roiPercentage: 24,
    durationDays: 120,
    biWeeklyPayout: 3500,
    popular: true,
    featured: false,
    features: ["24% ROI", "4 Months Duration", "Bi-weekly Payouts", "Priority Support"],
    active: true,
  },
  {
    name: "Silver Plan",
    description: "Balanced investment option",
    minInvestment: 100000,
    maxInvestment: 249999,
    roiPercentage: 30,
    durationDays: 180,
    biWeeklyPayout: 7500,
    popular: false,
    featured: false,
    features: ["30% ROI", "6 Months Duration", "Bi-weekly Payouts", "Dedicated Manager"],
    active: true,
  },
  {
    name: "Gold Plan",
    description: "Maximize your returns",
    minInvestment: 250000,
    maxInvestment: 499999,
    roiPercentage: 40,
    durationDays: 270,
    biWeeklyPayout: 15000,
    popular: false,
    featured: false,
    features: ["40% ROI", "9 Months Duration", "Bi-weekly Payouts", "VIP Support Access"],
    active: true,
  },
  {
    name: "Elite Plan",
    description: "For serious investors",
    minInvestment: 500000,
    maxInvestment: undefined,
    roiPercentage: 50,
    durationDays: 365,
    biWeeklyPayout: 35000,
    popular: false,
    featured: true,
    features: ["50% ROI", "12 Months Duration", "Bi-weekly Payouts", "Personal Account Manager", "Exclusive Deals"],
    active: true,
  },
];

export const DEFAULT_FARM_PROJECTS: Omit<FarmProject, "id" | "createdAt">[] = [
  {
    name: "Poultry Farm",
    location: "Ogun State",
    description: "Invest in our modern poultry farm with high-yield production",
    imageUrl: "https://images.unsplash.com/photo-1574629810360-7efbbe195018?auto=format&fit=crop&q=80&w=800",
    investmentAmount: 500000,
    roiPercentage: 78,
    durationDays: 24,
    spotsLeft: 12,
    active: true,
  },
  {
    name: "Rice Farm",
    location: "Kebbi State",
    description: "Large-scale rice plantation with modern farming techniques",
    imageUrl: "https://images.unsplash.com/photo-1574484284002-952d92456975?auto=format&fit=crop&q=80&w=800",
    investmentAmount: 800000,
    roiPercentage: 60,
    durationDays: 24,
    spotsLeft: 8,
    active: true,
  },
  {
    name: "Fish Farm",
    location: "Lagos State",
    description: "Aquaculture project with high-demand fish species",
    imageUrl: "https://images.unsplash.com/photo-1544551763-46a013bb70d5?auto=format&fit=crop&q=80&w=800",
    investmentAmount: 300000,
    roiPercentage: 80,
    durationDays: 10,
    spotsLeft: 25,
    active: true,
  },
];

export const ADMIN_USER_DATA = {
  email: "admin@agec.com",
  fullName: "Administrator",
  role: "admin" as const,
};
